Algoritmo "ExerciciosDeFixacao52"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : fazer um programa que armazene valores, depois mostrar o maior
// de cada linha na matriz
// Autor(a)    : Leonardo Araujo
// Data atual  : 28/07/2021
Var
   ord, i, j, maior : inteiro


Inicio
      escreva("Qual a ordem da matriz? ")
      leia(ord)
      
      para i de 0 ate o
      


Fimalgoritmo