Algoritmo "ExercicioDeFixacao30"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descricao    : Desenvolver um programa que mostre a sequancia de num impares
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/07/2021
Var
   i, x : inteiro


Inicio

      escreva("Digite o valor de X: ")
      leia(x)
      
      // mostrar sequencia de impares
      para i de 1 ate x passo i + 2 faca
           escreval(i)
      fimpara


Fimalgoritmo