Algoritmo "EXERCICIODEFIXACAO5"
// 
//  
// Descricao   : fazer um programa que mostre a soma dos valores recebidos de X e Y.
// Autor(a)    : Leonardo Araujo
// Data atual  : 23/06/2021
Var
   X, Y, Som : inteiro


Inicio
      escreva("Digite o valor de X: ")
      leia(X)
      escreva("Digite o valor de Y: ")
      leia(Y)
      
      // Calculo da soma
      som <- X + Y
      
      escreva("SOMA = ", som)


Fimalgoritmo