Algoritmo "ExercicioDeFixacao35"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descricao   : Fazer um pragrame que calcule fatorial de um valor lido
// Autor(a)    : Leonardo
// Data atual  : 06/07/2021
Var
  n, i, fatorial : inteiro


Inicio
      escreva("Digite o valor de N: ")
      leia(n)
      
      fatorial <- 1
      para i de 1 ate n faca
           fatorial <- fatorial * i
      fimpara
      
      escreva("FATORIAL = ", fatorial)
      
           
      


Fimalgoritmo