Algoritmo "ConhecendoFuncoesMatematicas"
// 
//  
// Descricao   : realizar alguns testes com as funcoes matematicas do visualg3
// Autor(a)    : Leonardo
// Data atual  : 22/06/2021
Var
  x, y, z, a, b, c, d : real

Inicio
      X <- 2.0
      y <- 3.0
      y <- 7.0
      
      a <- Exp(x, y)
      b <- RaizQ(Y)
      c <- Pi
      d <- Abs(z)
      
      escreval(a)
      escreval(b)
      escreval(c)
      escreval(d)
      
Fimalgoritmo