Algoritmo "ConhecendoFuncoesMatematicas2"
//
// Descricao   : realizar testes com funcoes do Visulag3
// Autor(a)    : Leonardo Araujo
// Data atual  : 22/06/2021
Var
   x, y, z, a, b, c, d : real


Inicio
      x <- 2.0
      y <- 3.0
      z <- -7.0
      
      a <- Exp(x, y)
      b <- RaizQ(y)
      d <- Pi
      d <- Abs(z)
      
      escreval(a)
      escreval(b)
      escreval(c)
      escreval(d)
Fimalgoritmo