Algoritmo "OperadoresCompativos"
// 
//  
// Descricao   : testes para ver o resultado dos sinais de comparacao
// Autor(a)    : Leonardo Araujo
// Data atual  : 25/06/2021
Var
   x : inteiro
   a, b, c, d: logico


Inicio

     x <- 5
     a <- x > 0
     b <- x = 3
     c <- 10 <= 30
     d <- x <> 2
     
     escreval("x > 0 : ", a)
     escreval("x = 3 : ", b)
     escreval("10 <= 30 :", c)
     escreval("x <> 2 :", d)
     
     

Fimalgoritmo