Algoritmo "ProcessandoDados4"
// 
//  
// Descricao   : compreender e corrigir o erro na divisao com resto, e em variavel inteira.
// Autor(a)    : Leonardo Araujo
// Data atual  : 22/06/2021
Var
   a, b, resultado : inteiro


Inicio
      a <- 5
      b <- 3
      
      // Troca de sinal da divisão para variavel receber valor inteiro
      resultado <- a \ b
      Escreva("resultado = ", resultado)



Fimalgoritmo