Algoritmo "RepeticaoEnquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descricao   : Testes com o comando enqunanto.
// Autor(a)    : Leonardo Araujo
// Data atual  : 29/06/2021
Var
   x, soma : inteiro


Inicio

      escreva("Digite o primeiro numero: ")
      leia(x)
      
      soma <- x
      enquanto x <> 0 faca
               escreva("Digite outro numero: ")
               leia(x)
               soma <- soma + x
      fimenquanto


Fimalgoritmo