Algoritmo "TesteSaidaExpressaoUnica"
// 
//  
// Descricao   : Fazer saída de uma unica informacao com variaaveis diferentes.
// Autor(a)    : Leonardo Araujo
// Data atual  : 21/06/2021
Var
   idade : inteiro
   salario : real
   nome : caractere


Inicio
      idade <- 32
      salario <- 4560.9
      nome <- "Maria silva"
      
      Escreval("A funcionaria ", nome, " ganha ", salario:8:2, " e tem ", idade, " de idade.")
      


Fimalgoritmo